version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7

clone_folder: c:\gopath\src\github.com\martinlindhe\wmi_exporter

install:
  - go version
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - go get -u github.com/kardianos/govendor

build_script:
  - govendor build -v +local
  - govendor test -v +local
  - ps: if($env:APPVEYOR_REPO_TAG -eq "True") { .\installer\build.ps1 -PathToExecutable .\wmi_exporter.exe -Version $env:APPVEYOR_REPO_TAG_NAME -Arch "amd64" }

artifacts:
  - name: Executable
    path: wmi_exporter.exe
  - path: Installer
    name: '.\installer\Output\wmi_exporter*.msi'

deploy:
  - provider: GitHub
    description: WMI Exporter version $(appveyor_build_version)
    artifact: Executable,Installer
    auth_token:
      secure: 'Hello, world'
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true
